device:
  name: bramble
  build_id: UP1A.231105.001
  platform_security_patch_level_override: 2023-12-01
  generation: pixel2020

platform:
  product_makefile: device/google/bramble/aosp_bramble.mk

includes:
  - common/gen5pixel.yml
