device:
  name: redfin
  build_id: UP1A.231105.001.B2
  prev_build_id: UP1A.231105.001
  platform_security_patch_level_override: 2023-12-01
  generation: pixel2020

platform:
  product_makefile: device/google/redfin/aosp_redfin.mk
  extra_product_makefiles:
    - device/google/redfin/wireless_charger/wireless_charger.mk

includes:
  - common/gen5pixel.yml
